version: "3.8"

services:
    master_branch:
      image: bmogul/mywebclass-simulation:master
      container_name: master_branch
      pull_policy: always
      restart: always
      ports:
        - "80:80"
    development_branch:
      image: bmogul/mywebclass-simulation:development
      container_name: development_branch
      pull_policy: always
      restart: always
      ports:
        - "8000:80"